export default function(router){
     router.map({
        '/login':{
             component:function(resolve){
                  require(['./login'],resolve);
             }
        },
        '/appraise':{
             component:function(resolve){
                  require(['./appraise'],resolve);
             }
        },
        '/transmit':{
             component:function(resolve){
                  require(['./transmit'],resolve);
             }
        },
        '/evaluate':{
             component:function(resolve){
                  require(['./evaluate'],resolve);
             }
        },
        '/enshrine':{
             component:function(resolve){
                  require(['./enshrine'],resolve);
             }
        },
        '/compile':{
             component:function(resolve){
                  require(['./compile'],resolve);
             }
        },
        '/edit':{
             component:function(resolve){
                  require(['./edit'],resolve);
             }
        },
        '/afflatus':{
             component:function(resolve){
                  require(['./afflatus'],resolve);
             }
        },
        '/song':{
             component:function(resolve){
                  require(['./song'],resolve);
             }
        },

        '/article':{
             component:function(resolve){
                 require(['./article'],resolve);
             }
        },
        '/erry':{
             component:function(resolve){
                  require(['./erry'],resolve);
             }
        },
        '/home':{
             component:function(resolve){
                require(['./home'],resolve);
             },
             subRoutes:{
                '/note':{
                       component:function(resolve){
                          require(['./note'],resolve);
                       }
                    },
                '/production':{
                       component:function(resolve){
                          require(['./production'],resolve);
                       }
                    },
                '/foo':{
                       component:function(resolve){
                          require(['./foo'],resolve);
                       }
                    },
                '/bar':{
                       component:function(resolve){
                           require(['./bar'],resolve);
                       }
                   },
                '/my-music':{
                       component:function(resolve){
                           require(['./my-music'],resolve);
                       }
                   },
                '/film':{
                       component:function(resolve){
                           require(['./film'],resolve);
                       }
                   },
                '/setting':{
                       component:function(resolve){
                           require(['./setting'],resolve);
                       }
                   }
             }
        }
        
     }),
    router.redirect({
           "*":"./erry",
           "/":"./login"
    })  
}